name: AWS assume IAM role OpenID Connect (OIDC)

inputs:
  web-identity-role-arn:
    description: GitHub OpenID Connect target IAM role ARN.
    required: true
  assume-role-arn:
    description: Target IAM role ARN to assume.
    default:
  assume-role-duration-seconds:
    description: Assumed IAM role session duration.
    default: 1200
  assume-role-session-name:
    description: Assumed IAM role session name.
    default: github-actions
  aws-region:
    description: Desired AWS region.
    required: true

runs:
  using: composite
  steps:
    - name: Execute
      run: |
        INPUT_WEB_IDENTITY_ROLE_ARN="${{ inputs.web-identity-role-arn }}" \
        INPUT_ASSUME_ROLE_ARN="${{ inputs.assume-role-arn }}" \
        INPUT_ASSUME_ROLE_DURATION_SECONDS="${{ inputs.assume-role-duration-seconds }}" \
        INPUT_ASSUME_ROLE_SESSION_NAME="${{ inputs.assume-role-session-name }}" \
        INPUT_AWS_REGION="${{ inputs.aws-region }}" \
          "${{ github.action_path }}/main.py"
      shell: bash
